### PR TITLE
Adding Bobby Johnson (Auth0Bobby)

### PR DESCRIPTION
**Pull request by NotMyself**
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

### CODE REVIEW

**Comment by NotMyself** [comment]
Fixed up.

**Comment by mblayman** [comment]
Did you forget to push? There are no changes to this branch.

**Comment by NotMyself** [comment]
Ok that was weird. Looks correct now.

**Comment by mblayman** [comment]
The diff looks off to me. Anthony's entire section is still deleted. https://github.com/bnb/awesome-developer-streams/pull/134/files#diff-04c6e90faac2675aa89e2176d2eec7d8L189

**Comment by NotMyself** [comment]
Let me back up and try this again from an actual branch. Trying to use the github editor to merge is confusing me I think.

**Pull request closed without merging**
