### PR TITLE
Add shields.io Twitch status badges.

### PR DESCRIPTION
**Pull request by andyli**
Result can be viewed at https://github.com/andyli/awesome-developer-streams/tree/shields.io#developers-that-stream

### CODE REVIEW

**Comment by mblayman** [comment]
Hi, @andyli, thanks for the contribution.

I'm on the fence about this change. In #188, we focused on the possibility of adding icons next to links. For now, we decided against it because of the added complexity for new contributions (i.e., more markup that people may not be familiar with) and because the icons don't provide a clean and aligned layout with the text.

I feel similarly with this branch. The shield doesn't align with the text. *More importantly*, I'm not convinced of the added utility from the change. I checked out the preview from top to bottom and 3 out of the hundreds were listed as "live." Every other streamer was listed as "offline." That seemed discouraging to me. I think of this list less as "here's what going on *right now*" and more of "here are cool streamers you might want to check out." I'd suggest we nudge people toward something like https://shipstreams.com/ to see what's going on currently.

I also get the sense this biases heavily toward Twitch. While most of the streamers are on Twitch, there are other streamers on YouTube and Instagram.

Those points make me lean +0 or -1 on this branch. I'd like to hear what @bnb and @surlydev think.

**Comment by bnb** [comment]
I would honestly _love_ to see a bot or GitHub Action that PR's this on the Twitch event (from their API) when someone goes live, so that way it'd be searchable. Either by adding something like "🔴 Live Now" next to their name or by moving them into a section at the top of the README that is for streamers that are currently live.

I've really wanted to include this somehow in a way that would make it easy to find people who are currently streaming. Unfortunately, that's not been particularly accessible – and, while this implementation is awesome (I saw that @clarkio was live because I was scrolling 😅), I'm not sure that it adds a _ton_ since you've got to scroll through the entire list to find just a few people who may or may not be online.

**Comment by jasonwilliams** [comment]
>That seemed discouraging to me. I think of this list less as "here's what going on right now" and more of "here are cool streamers you might want to check out." I'd suggest we nudge people toward something like https://shipstreams.com/ to see what's going on currently.

I disagree with this, i fully expect that a list this big only a small percentage will be online.
Sometimes i just come here for inspiration (not looking for anyone specifically), if i only saw 2 or 3 online right now i would be tempted to click through and see what they're doing. i wouldn't be discouraged if only 1 or 2% of this are on line. 

Actually i would say the opposite, the bigger this list gets the more likely half the people on it don't even stream anymore, inactive and it becomes more useless (i already know a couple on this list who stopped streaming), so seeing who's active is a BIG help!

I think its a great addition personally.

**Comment by mblayman** [comment]
@jasonwilliams, that's a fair point.

Maybe this would be more appealing to me if there were a section of "Live Right Now" that would list all the live streamers in a single place. That would definitely take something like an unusual configuration of GitHub Actions to work.

**Comment by jasonwilliams** [comment]
Is there a twitch API we can throw a list of users to and it tells us which ones are online?

**Comment by bnb** [comment]
Yep, you can use the Get Streams API ([ref](https://dev.twitch.tv/docs/api/reference/#get-streams)) and pass in a username to see if they're live. I actually did this recently with a friend who I'm helping learn JavaScript – you can see it here: https://github.com/bnb/discord-streams/blob/master/lib/twitchUtil.js

**Comment by jasonwilliams** [comment]
@bnb sure, but im talking for all the users on the front page.
Will you need to call the API multiple times? or can we pass an array of users?

Wont you get rate limited if you call that for every user on the list?

**Comment by bnb** [comment]
I mean they don't allow unauthenticated requests for the Get Streams API, so the [upper limit is 800/minute](https://dev.twitch.tv/docs/api/guide/#rate-limits). Even if we only pass one, AFAIK we're currently under 800 streamers listed. Could build a queue and overflow at 400 into another bucket of requests.

Seems like it would be relatively ideal to build a module to do this, then consume that module in a GitHub Action or GitHub Bot using something like [Probot](https://probot.github.io/) – my file in that repo could absolutely be a starting place for that.

**Comment by surlydev** [comment]
I was looking at this, and I like the idea in principle, but scrolling through the list and finding the live streamers was taking too long, so I took all the shields URLs and moved them to the end to create a sort of 'lucky dip' of Live Twitch streamers.

image


If you load my branch ( https://github.com/surlydev/awesome-developer-streams/tree/experiment/shields ) and then Ctrl+End to the end of the page it's 'fun' watching the icons populate.

They don't link through to the streams, unfortunately, it was just an idea I had, but it would become a maintenance nightmare. So, I'm not going to add it to the list.

**Comment by surlydev** [comment]
I’m going to close this just because the weather edits are now far behind.

Please don’t be discouraged, I agree with Matt that the clean look of the list is a major factor, but I’m thinking of taking this Shields Idea and creating a twitch-specific page that shows online streamers .

Thanks for the inspiration.

**Pull request closed without merging**
