### PR TITLE
Adding DevChatter Stream

### PR DESCRIPTION
**Pull request by benrick**

### CODE REVIEW

**Comment by bnb** [comment]
Hey there @benrick - new PRs usually go at the end of the document. Would you mind moving both the nav ToC item and the block item to the end? Thanks!

**Comment by benrick** [comment]
No problem. Only reason I didn't do the bottom is that merge conflicts would happen.

**Comment by benrick** [comment]
OK, @bnb I resolved the conflict after moving to the bottom. I can move it down to the bottom again after resolving the conflict.

**Comment by benrick** [comment]
Should be ready to merge again.

**Comment by bnb** [comment]
Awesome, thanks! I generally don't mind fixing merge conflicts, it's p easy in this repo 😅 

Merging!

**Pull request merged**
