### PR TITLE
Adds Twilio Streamers to the list

### PR DESCRIPTION
**Pull request by clw895**
Adds the following streamers and their tech stacks of choice from Twilio:
- Brent Schooley
- Corey Weathers
- Gary Hockin
- Layla Porter

### CODE REVIEW

**Comment by surlydev** [comment]
Sorry for the initial delay responding. I had surgery 3 weeks ago and I've been recuperating.

Yep, check out the file on your branch, you'll see the links you added aren't showing as links because of a space between the [name] and the (name link) parts of the markdown. Please remove this space.

You also forgot to add the main section for each of the sections.

Take a look at the index entry for CodeRushed

`- [CodeRushed](#coderushed-mark-miller) - **streaming:** C#, .Net Core, ASP.Net Core, TypeScript, JavaScript, CodeRush dog-fooding
`
 to see how the head of the main entry looks when you use multiple names/aliases such as Chef Brent.
`### CodeRushed (Mark Miller)
`

**Comment by clw895** [comment]
Hope you’re feeling better. I’ll used CodeRushed as the example and fix that.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by clw895** [comment]
Oh snap – I totally spaced on this. About to fix this today.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
From: Corey Weathers <clw895@msn.com>
Sent: Monday, February 24, 2020 10:57:09 AM
To: bnb/awesome-developer-streams <reply@reply.github.com>; bnb/awesome-developer-streams <awesome-developer-streams@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [bnb/awesome-developer-streams] Adds Twilio Streamers to the list (#221)


Hope you’re feeling better. I’ll used CodeRushed as the example and fix that.



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10



________________________________

**Comment by clw895** [comment]
Updated with a second pr. Feel free to review and let me know

**Comment by surlydev** [comment]
Getting closer Mr Weathers, getting closer. 🥉 

Layla's GitHub link doesn't work.

Brent's Twitter is @chefbrenttv - @chefbrent is a different Brent, who is also a chef, and as far as I can tell, he's not affiliated with Twilio in any way.

Please change the Instagram link on Brent's entry , removing the :ChefBrent from Instagram:ChefBrent as well as trying to keep the links clean, the text is wrong as it's ChefBrentTV. The link is fine, but the text is misleading.

I'm going to let you off the highlighted bits for now, as I'm not sure if there's a hard and fast rule where someone has multiple accounts (even though it's not the style used elsewhere on the list) ... however you might want to change the text against the YouTube link for Twilio as the account name is Twilio not Twilio TV.

image

I'm disappointed you didn't put "Hurricane" in your own entry ;)

- see me after class.

**Comment by clw895** [comment]
Just updated Brent's entry to fix those errors. I didn't put hurricane in mine cause I've not leaned into it on my profile at all. But when I do, i'll update my entry here for sure

**Comment by surlydev** [comment]
🏅

**Pull request merged**
